# Generated by Django 4.2.7 on 2023-11-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default_item.jpg', upload_to='item_pics'),
        ),
    ]
