# Generated by Django 4.2.7 on 2023-11-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_image_item_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_image',
            new_name='image',
        ),
    ]
