# Generated by Django 4.2.7 on 2023-11-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_report_items_shoppingcart_order'),
        ('inventory', '0004_rename_item_image_item_image'),
    ]

    operations = [
    ]
